In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import numpy as np
import datetime
import time
import pickle
import os
import seaborn as sns
from scipy.interpolate import make_interp_spline
from tabulate import tabulate
import sys
sys.path.append("src")
from data_generation import *
from neural_networks import *
from estimation import *

pd.options.mode.chained_assignment = None
os.chdir('Result_Tables/')

In [2]:
def feature_generation_endo(J, K, M, seed):
    # J is number of products per markets (assume each market has the same number of products but different products)
    # K is number of features (excluding price)
    # M is the number of markets (assume each market has different sets of products)
    np.random.seed(seed)

    Total_J = J * M
    x_1 = np.random.normal(loc=0, scale=1, size=(Total_J , K))
    mu = np.random.normal(loc=0, scale=1, size = Total_J)
    z = np.random.uniform(0,4,size = Total_J)
    price = z + mu
    
    X = pd.DataFrame(x_1)
    X['price'] = price

    return X, mu, z

In [10]:
def endo_iteration(mode, J, M, K, seed, dg, params, datax, delta):
    setup = [J, K, M, str(dg).split()[1], seed]
    data_train, data_test = split_train_test(datax, p = 0.8)
    ### step 2: train models 
    m1_deep, loss_deep = train_deep(data_train)
     
    ### step 3: evaluation
    data = data_train.copy()

    y_pred_deep1 = pred_deep(data, m1_deep)
    error_deep1 = get_errors(y_pred_deep1, data['Y'])
    
    train_pred_df = pd.DataFrame({'true':data['Y'], 'pred_deep':y_pred_deep1})
    
    train_pred_df.to_csv(mode + "_train"+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".csv")

    print("J=", data['J'],"K=", data['K'],"M=", data['M'], "\n", str(dg).split()[1], 'training error',
          "deep error: ", error_deep1[1], "\n") 
    
    data = data_test.copy()

    y_pred_deep1 = pred_deep(data, m1_deep)
    error_deep1 = get_errors(y_pred_deep1, data['Y'])
    
    
    print("J=", data['J'],"K=", data['K'],"M=", data['M'], "\n",  str(dg).split()[1], 'test error'
          "deep error: ", error_deep1[1], "\n") 
    
    test_pred_df = pd.DataFrame({'true':data['Y'], 'pred_deep':y_pred_deep1})
    
    test_pred_df.to_csv(mode + "_test"+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".csv")
    
    error_all = setup + error_deep1 
    error_file_name = mode + '_error_'+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".pickle"
    
    with open(error_file_name, "wb") as f:
        # dump the dictionary into the file using pickle.dump()
        pickle.dump(error_all, f)
    
    
    model_list = [m1_deep]
    model_file_name = mode + '_model_'+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".pickle"
    
    with open(model_file_name, "wb") as f:
        # dump the dictionary into the file using pickle.dump()
        pickle.dump(model_list, f)
        

    ### step 5: elasticity
    J = data_train['J']
    large_record = pd.DataFrame(columns = ['market_id','i','j','old_price','new_price','type',
                                           'true_elasticity','pred_elasticity_deep','price_i'])
    for prod_id in range(J):
        data_train = cal_true_elasticity(data_train, dg, prod_id, delta, seed)
        record = cal_elasticity_record(data_train, pred_deep, model_list[0], prod_id, delta)
        record = record.rename(columns={'pred_elasticity': 'pred_elasticity_deep'})
        record['i'] = prod_id
        record['j'] = record.index % data_train['J']
        large_record = pd.concat([large_record, record]).reset_index(drop=True)

    large_record['error_deep'] = large_record['pred_elasticity_deep'] - large_record['true_elasticity']
    
    large_record.to_csv(mode + '_elas_record_'+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".csv", index = False)
    
    elas_all = large_record.copy()
    elas_all['ae_deep'] = np.abs(elas_all['error_deep'])
    
    elas_all.to_csv(mode + '_elas_all' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv', index = False)
    
    elas_valid = elas_all.loc[(elas_all.true_elasticity.isna()==False) & (np.isfinite(elas_all.true_elasticity) == True)].copy()
    
    elas_rslt_median = elas_valid.groupby(['type'])[['ae_deep']].median().reset_index()
    elas_rslt_mean = elas_valid.groupby(['type'])[['ae_deep']].mean().reset_index()
    
    print('elas_mean', elas_rslt_mean)
    print('elas_median', elas_rslt_median)
    
    return 1

In [8]:
def endo_data_generation(J, K, M, seed, dg, params):
    X, mu, z = feature_generation_endo(J, K, M, seed)
            
    X_comp = X.copy()
    X_comp.insert(loc=K, column=K, value=mu)

    iv_model = sm.OLS(X['price'], z).fit()
    residuals = iv_model.resid

    X_endo = X.copy()
    X_endo.insert(loc=K, column=K, value= residuals ) 

    data_comp = dg(X_comp, params, J, K+1, M, seed)
    data_endo = data_comp.copy()
    data_endo['X'] = X_endo
    
    data_wrong = data_comp.copy()
    data_wrong['X'] = X.copy()
    data_wrong['K'] = K
    
    return data_endo, data_comp, data_wrong

In [28]:
def endo_report(J, K, M, seed_list, dg):
    
    elas_all = pd.DataFrame()
    error_df = pd.DataFrame(columns = ['J', 'K', 'M', 'dg', 'seed',"mse_deep","mae_deep"])
    o_K = K
    for mode in ['endo','comp','wrong']:
        for seed in seed_list:
            if mode !='wrong':
                K = o_K+1
            else:
                K = o_K
            
            error_file = mode + '_error_'+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".pickle"
            elas_file = mode + '_elas_record_'+ 'J' + str(J) + 'K' +  str(K) +'M' + str(M) + '_'+str(seed) + str(dg).split()[1] +".csv"
            elas_record = pd.read_csv(elas_file)
            elas_record['seed'] = seed
            with open(error_file, 'rb') as f:
                error_all = pickle.load(f) 

            error_df = pd.concat([error_df, pd.DataFrame([error_all], columns= error_df.columns)])
            elas_all = pd.concat([elas_all, elas_record])
            

        error_df.to_csv(mode + '_error_df' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv')
        elas_all['ae_deep'] = np.abs(elas_all['error_deep'])

        elas_all.to_csv(mode + '_elas_all' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv', index = False)
    
        elas_valid = elas_all.loc[(elas_all.true_elasticity.isna()==False) & (np.isfinite(elas_all.true_elasticity) == True)].copy()

        elas_rslt_mean = elas_valid.groupby(['type'])[['ae_deep']].mean().reset_index()

        elas_rslt_mean.to_csv(mode+'_elas_mae_' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv', index = False)

    return 1

In [5]:
seed_list = [7456,145609, 214341, 237639, 148649, 763490, 677253, 560404, 591830,
    84947,  26672, 184535, 874369,  39876, 738836, 100589, 812811,
    75122, 182935, 911677]

dg_list = [rcl] 
JKM_list = [[10,10,100]]
delta = 0.1 

hyper_params = {'hidden_size': 256, 'num_hidden_layers': 5, 'n_epochs': 2000, 'learning_rate': 0.0001}

os.chdir("/mnt/sdb1/colab-project/rslt_0414/endo")

In [11]:
for [J, K, M] in JKM_list:
    for dg in dg_list:
        for i in range(len(seed_list)):
            seed = seed_list[i]
            params = [np.random.normal(0,1,K+3) / (K * 2), np.ones(K+3)]
            params[0][-1] = -1
            data_endo, data_comp, data_wrong = endo_data_generation(J, K, M, seed, dg, params)
            endo_iteration('endo',J, M, K+1, seed, dg, params, data_endo, delta)
            endo_iteration('comp',J, M, K+1, seed, dg, params, data_comp, delta)
            endo_iteration('wrong',J, M, K, seed, dg, params, data_wrong, delta)
            print(J, K, M, i, 'finished', datetime.datetime.now())

J= 10 K= 11 M= 80
 rcl training error deep error:  9.981734352400576e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.0265406391651378

elas_mean     type  ae_deep
0  cross   0.0591
1   self   0.2159
elas_median     type  ae_deep
0  cross   0.0376
1   self   0.1304
J= 10 K= 11 M= 80
 rcl training error deep error:  7.231927437927537e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.031221956528521066

elas_mean     type  ae_deep
0  cross   0.0665
1   self   0.2302
elas_median     type  ae_deep
0  cross   0.0400
1   self   0.1491
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00018633844655526396

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.030513544192329503

elas_mean     type  ae_deep
0  cross   5.7926
1   self   6.6685
elas_median     type  ae_deep
0  cross   4.0335
1   self   4.3525
10 10 100 0 finished 2024-02-11 18:44:21.848654
J= 10 K= 11 M= 80
 rcl training error deep error:  8.116366497350936e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.024295627469134724

elas_mean     type  ae_deep
0  cross   0.0580
1   self   0.2482
elas_median     type  ae_deep
0  cross   0.0377
1   self   0.1488
J= 10 K= 11 M= 80
 rcl training error deep error:  9.365076296055397e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.024731265815634732

elas_mean     type  ae_deep
0  cross   0.0605
1   self   0.2644
elas_median     type  ae_deep
0  cross   0.0378
1   self   0.1575
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00022417194109291744

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.026926538868081003

elas_mean     type  ae_deep
0  cross   5.7956
1   self   6.6648
elas_median     type  ae_deep
0  cross   4.0011
1   self   4.3760
10 10 100 1 finished 2024-02-11 18:46:11.005258
J= 10 K= 11 M= 80
 rcl training error deep error:  0.0004833295007939485

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.029689218745844435

elas_mean     type  ae_deep
0  cross   0.0766
1   self   0.2099
elas_median     type  ae_deep
0  cross   0.0528
1   self   0.1320
J= 10 K= 11 M= 80
 rcl training error deep error:  9.930189463661295e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.027723020136708507

elas_mean     type  ae_deep
0  cross   0.0633
1   self   0.2996
elas_median     type  ae_deep
0  cross   0.0384
1   self   0.1917
J= 10 K= 10 M= 80
 rcl training error deep error:  0.0001222297584678398

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.02754139003211793

elas_mean     type  ae_deep
0  cross   5.9327
1   self   6.8865
elas_median     type  ae_deep
0  cross   4.0172
1   self   4.4352
10 10 100 2 finished 2024-02-11 18:47:58.458077
J= 10 K= 11 M= 80
 rcl training error deep error:  9.358960179045529e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.021364259421926005

elas_mean     type  ae_deep
0  cross   0.0569
1   self   0.2177
elas_median     type  ae_deep
0  cross   0.0369
1   self   0.1573
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00011821493000433194

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023268426194380274

elas_mean     type  ae_deep
0  cross   0.0553
1   self   0.2176
elas_median     type  ae_deep
0  cross    0.034
1   self    0.140
J= 10 K= 10 M= 80
 rcl training error deep error:  9.188540799314634e-05

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.02376056655645039

elas_mean     type  ae_deep
0  cross   5.5656
1   self   6.4298
elas_median     type  ae_deep
0  cross   3.8519
1   self   4.1760
10 10 100 3 finished 2024-02-11 18:49:49.243767
J= 10 K= 11 M= 80
 rcl training error deep error:  9.421421487313791e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02376375525054948

elas_mean     type  ae_deep
0  cross   0.0735
1   self   0.2065
elas_median     type  ae_deep
0  cross   0.0462
1   self   0.1355
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00035194151464899403

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.029830980006953712

elas_mean     type  ae_deep
0  cross   0.0897
1   self   0.2191
elas_median     type  ae_deep
0  cross   0.0539
1   self   0.1345
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00010511477048275869

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.029840877045420232

elas_mean     type  ae_deep
0  cross   5.6128
1   self   6.4787
elas_median     type  ae_deep
0  cross   3.9353
1   self   4.3976
10 10 100 4 finished 2024-02-11 18:51:44.117226
J= 10 K= 11 M= 80
 rcl training error deep error:  8.651507949951284e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.024088460370204796

elas_mean     type  ae_deep
0  cross   0.0848
1   self   0.2754
elas_median     type  ae_deep
0  cross   0.0578
1   self   0.1516
J= 10 K= 11 M= 80
 rcl training error deep error:  0.0002457691080365429

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02487118267195012

elas_mean     type  ae_deep
0  cross   0.0613
1   self   0.1987
elas_median     type  ae_deep
0  cross   0.0390
1   self   0.1299
J= 10 K= 10 M= 80
 rcl training error deep error:  0.0007377787848696343

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.028667479297320293

elas_mean     type  ae_deep
0  cross   5.5089
1   self   6.3359
elas_median     type  ae_deep
0  cross   3.8317
1   self   4.1785
10 10 100 5 finished 2024-02-11 18:53:32.692179
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00022398054531255133

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02685554367380271

elas_mean     type  ae_deep
0  cross   0.0674
1   self   0.2679
elas_median     type  ae_deep
0  cross   0.0433
1   self   0.1546
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00017578366966362975

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02448762831283913

elas_mean     type  ae_deep
0  cross   0.0642
1   self   0.2293
elas_median     type  ae_deep
0  cross   0.0396
1   self   0.1406
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00025145892652112494

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.03170701488563834

elas_mean     type  ae_deep
0  cross   5.7241
1   self   6.6252
elas_median     type  ae_deep
0  cross   3.9061
1   self   4.3860
10 10 100 6 finished 2024-02-11 18:55:20.948976
J= 10 K= 11 M= 80
 rcl training error deep error:  0.0008200612204722745

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02657324158041414

elas_mean     type  ae_deep
0  cross   0.0723
1   self   0.2338
elas_median     type  ae_deep
0  cross   0.0476
1   self   0.1594
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00014683498714119876

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02419133332850108

elas_mean     type  ae_deep
0  cross   0.0658
1   self   0.2097
elas_median     type  ae_deep
0  cross   0.0418
1   self   0.1387
J= 10 K= 10 M= 80
 rcl training error deep error:  8.669861030078296e-05

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.025969692468503443

elas_mean     type  ae_deep
0  cross   5.5497
1   self   6.4407
elas_median     type  ae_deep
0  cross   4.0449
1   self   4.3389
10 10 100 7 finished 2024-02-11 18:57:07.112574
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00016967159243290483

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02481533681510558

elas_mean     type  ae_deep
0  cross   0.0618
1   self   0.2358
elas_median     type  ae_deep
0  cross   0.0381
1   self   0.1602
J= 10 K= 11 M= 80
 rcl training error deep error:  3.4241865425452065e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.025925029386663755

elas_mean     type  ae_deep
0  cross   0.0592
1   self   0.2276
elas_median     type  ae_deep
0  cross    0.035
1   self    0.148
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00018290749968276023

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.027749557525938995

elas_mean     type  ae_deep
0  cross   6.2246
1   self   7.2461
elas_median     type  ae_deep
0  cross   4.0313
1   self   4.4669
10 10 100 8 finished 2024-02-11 18:59:09.039817
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00010291667625277034

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.028494717734592157

elas_mean     type  ae_deep
0  cross   0.0654
1   self   0.2303
elas_median     type  ae_deep
0  cross   0.0421
1   self   0.1407
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00031954468258765556

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.027154929660666658

elas_mean     type  ae_deep
0  cross   0.0623
1   self   0.2541
elas_median     type  ae_deep
0  cross   0.0372
1   self   0.1550
J= 10 K= 10 M= 80
 rcl training error deep error:  0.0001356110390501338

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.029752570816618425

elas_mean     type  ae_deep
0  cross   5.9737
1   self   6.9230
elas_median     type  ae_deep
0  cross   4.2013
1   self   4.5944
10 10 100 9 finished 2024-02-11 19:01:06.805536
J= 10 K= 11 M= 80
 rcl training error deep error:  9.260871140298615e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.028083140927892304

elas_mean     type  ae_deep
0  cross   0.0682
1   self   0.2261
elas_median     type  ae_deep
0  cross   0.0451
1   self   0.1310
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00015074798661482704

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02503010711399318

elas_mean     type  ae_deep
0  cross   0.0538
1   self   0.2250
elas_median     type  ae_deep
0  cross   0.0342
1   self   0.1444
J= 10 K= 10 M= 80
 rcl training error deep error:  8.636643905276096e-05

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.027721676100389635

elas_mean     type  ae_deep
0  cross   6.0900
1   self   7.0748
elas_median     type  ae_deep
0  cross   4.0384
1   self   4.4406
10 10 100 10 finished 2024-02-11 19:02:57.886053
J= 10 K= 11 M= 80
 rcl training error deep error:  4.552304170802831e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023049627470132086

elas_mean     type  ae_deep
0  cross   0.0615
1   self   0.2293
elas_median     type  ae_deep
0  cross   0.0369
1   self   0.1406
J= 10 K= 11 M= 80
 rcl training error deep error:  5.350916832792652e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02170573728970982

elas_mean     type  ae_deep
0  cross   0.0573
1   self   0.2225
elas_median     type  ae_deep
0  cross   0.0336
1   self   0.1363
J= 10 K= 10 M= 80
 rcl training error deep error:  0.0002763980330210153

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.023855497777325853

elas_mean     type  ae_deep
0  cross   6.0320
1   self   6.9574
elas_median     type  ae_deep
0  cross   4.2160
1   self   4.5469
10 10 100 11 finished 2024-02-11 19:04:45.226035
J= 10 K= 11 M= 80
 rcl training error deep error:  6.0881836585101367e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.024427722513957

elas_mean     type  ae_deep
0  cross   0.0573
1   self   0.1973
elas_median     type  ae_deep
0  cross   0.0352
1   self   0.1296
J= 10 K= 11 M= 80
 rcl training error deep error:  6.995519860472592e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.021946106870081483

elas_mean     type  ae_deep
0  cross   0.0588
1   self   0.2168
elas_median     type  ae_deep
0  cross   0.0362
1   self   0.1435
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00010872312626592642

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.03991782397692499

elas_mean     type  ae_deep
0  cross   5.7442
1   self   6.6206
elas_median     type  ae_deep
0  cross   3.8920
1   self   4.1821
10 10 100 12 finished 2024-02-11 19:06:39.624804
J= 10 K= 11 M= 80
 rcl training error deep error:  6.928557350146879e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.025019014130810677

elas_mean     type  ae_deep
0  cross   0.0642
1   self   0.2638
elas_median     type  ae_deep
0  cross   0.0408
1   self   0.1548
J= 10 K= 11 M= 80
 rcl training error deep error:  9.539503139167235e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023802675389616695

elas_mean     type  ae_deep
0  cross   0.0552
1   self   0.2176
elas_median     type  ae_deep
0  cross   0.0347
1   self   0.1413
J= 10 K= 10 M= 80
 rcl training error deep error:  3.551681512443578e-05

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.025327390255649472

elas_mean     type  ae_deep
0  cross   5.8397
1   self   6.7022
elas_median     type  ae_deep
0  cross   4.0428
1   self   4.3399
10 10 100 13 finished 2024-02-11 19:08:27.841163
J= 10 K= 11 M= 80
 rcl training error deep error:  5.023405645446958e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02386617348323745

elas_mean     type  ae_deep
0  cross   0.0568
1   self   0.2103
elas_median     type  ae_deep
0  cross   0.0341
1   self   0.1299
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00010197377189130267

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02415104040263104

elas_mean     type  ae_deep
0  cross   0.0686
1   self   0.1939
elas_median     type  ae_deep
0  cross   0.0394
1   self   0.1280
J= 10 K= 10 M= 80
 rcl training error deep error:  0.000134287054210499

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.025229266705377573

elas_mean     type  ae_deep
0  cross   6.0230
1   self   6.9228
elas_median     type  ae_deep
0  cross   4.0921
1   self   4.4798
10 10 100 14 finished 2024-02-11 19:10:15.249134
J= 10 K= 11 M= 80
 rcl training error deep error:  0.0001176790901467754

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.028911405129735012

elas_mean     type  ae_deep
0  cross   0.0795
1   self   0.2491
elas_median     type  ae_deep
0  cross   0.0512
1   self   0.1529
J= 10 K= 11 M= 80
 rcl training error deep error:  7.902358510103078e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02210239871121837

elas_mean     type  ae_deep
0  cross   0.0563
1   self   0.2276
elas_median     type  ae_deep
0  cross   0.0322
1   self   0.1416
J= 10 K= 10 M= 80
 rcl training error deep error:  6.347422063038994e-05

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.02672264609547659

elas_mean     type  ae_deep
0  cross   5.6731
1   self   6.5804
elas_median     type  ae_deep
0  cross   3.9415
1   self   4.2550
10 10 100 15 finished 2024-02-11 19:12:02.240341
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00017409311414463727

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023162349913534188

elas_mean     type  ae_deep
0  cross   0.0613
1   self   0.2174
elas_median     type  ae_deep
0  cross   0.0400
1   self   0.1503
J= 10 K= 11 M= 80
 rcl training error deep error:  5.606245896957802e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023650690417259212

elas_mean     type  ae_deep
0  cross   0.0634
1   self   0.2361
elas_median     type  ae_deep
0  cross   0.0392
1   self   0.1598
J= 10 K= 10 M= 80
 rcl training error deep error:  0.000125605246813007

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.02414396090743168

elas_mean     type  ae_deep
0  cross   5.6804
1   self   6.5574
elas_median     type  ae_deep
0  cross   4.2043
1   self   4.7336
10 10 100 16 finished 2024-02-11 19:13:49.360625
J= 10 K= 11 M= 80
 rcl training error deep error:  8.435917622834305e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02761590827388816

elas_mean     type  ae_deep
0  cross   0.0684
1   self   0.2405
elas_median     type  ae_deep
0  cross   0.0454
1   self   0.1477
J= 10 K= 11 M= 80
 rcl training error deep error:  7.497373095938925e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.023025326365787458

elas_mean     type  ae_deep
0  cross   0.0702
1   self   0.2066
elas_median     type  ae_deep
0  cross   0.0413
1   self   0.1366
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00016165401241625306

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.0282114939685623

elas_mean     type  ae_deep
0  cross   5.8738
1   self   6.8487
elas_median     type  ae_deep
0  cross   3.8724
1   self   4.4394
10 10 100 17 finished 2024-02-11 19:15:35.400874
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00010973850999813632

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02061649720404314

elas_mean     type  ae_deep
0  cross   0.0599
1   self   0.2343
elas_median     type  ae_deep
0  cross   0.0386
1   self   0.1407
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00011189530877701635

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.0318012565119447

elas_mean     type  ae_deep
0  cross   0.0885
1   self   0.2321
elas_median     type  ae_deep
0  cross   0.0550
1   self   0.1555
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00013014687117476507

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.03036442061629651

elas_mean     type  ae_deep
0  cross   5.8590
1   self   6.7751
elas_median     type  ae_deep
0  cross   4.0751
1   self   4.3862
10 10 100 18 finished 2024-02-11 19:17:26.800001
J= 10 K= 11 M= 80
 rcl training error deep error:  0.00011906107150294055

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.030008540740477842

elas_mean     type  ae_deep
0  cross   0.0857
1   self   0.2045
elas_median     type  ae_deep
0  cross   0.0520
1   self   0.1293
J= 10 K= 11 M= 80
 rcl training error deep error:  5.923149326010451e-05

J= 10 K= 11 M= 20
 rcl test errordeep error:  0.02431522421552463

elas_mean     type  ae_deep
0  cross   0.0701
1   self   0.2157
elas_median     type  ae_deep
0  cross   0.0420
1   self   0.1386
J= 10 K= 10 M= 80
 rcl training error deep error:  0.00010452808371430585

J= 10 K= 10 M= 20
 rcl test errordeep error:  0.027934718168662498

elas_mean     type  ae_deep
0  cross   5.3794
1   self   6.0924
elas_median     type  ae_deep
0  cross   3.5144
1   self   3.9425
10 10 100 19 finished 2024-02-11 19:19:27.040700

FileNotFoundError: [Errno 2] No such file or directory: 'elas_record_J10K10M100_7456rcl.csv'

In [29]:
for [J, K, M] in JKM_list:
    for dg in dg_list:
        endo_report(J, K, M, seed_list, dg)

In [50]:
mode = 'comp'
o_K = 10
for mode in ['endo','comp','wrong']:
    for [J, K, M] in JKM_list:
        for dg in dg_list:
            if mode !='wrong':
                K = o_K+1
            else:
                K = o_K
            elas_all = pd.read_csv(mode + '_elas_all' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv')
            elas_valid = elas_all.loc[(elas_all.true_elasticity.isna()==False) & (np.isfinite(elas_all.true_elasticity) == True)].copy()
            elas_rslt_std = elas_valid.groupby(['type'])[['error_deep']].std().reset_index()
            print(mode, elas_rslt_std)

endo     type  error_deep
0  cross      0.1033
1   self      0.3516
comp     type  error_deep
0  cross      0.1039
1   self      0.3469
wrong     type  error_deep
0  cross      4.4306
1   self      5.1901

In [49]:
mode = 'comp'
o_K = 10
for mode in ['endo','comp','wrong']:
    for [J, K, M] in JKM_list:
        for dg in dg_list:
            if mode !='wrong':
                K = o_K+1
            else:
                K = o_K
            path = mode+'_elas_mae_' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv'
            df = pd.read_csv(path)
            print(mode, df)

endo     type  ae_deep
0  cross   0.0669
1   self   0.2307
comp     type  ae_deep
0  cross   0.0657
1   self   0.2290
wrong     type  ae_deep
0  cross   1.9751
1   self   2.3832

In [48]:
for mode in ['endo','comp','wrong']:
      
    if mode !='wrong':
        K = o_K+1
    else:
        K = o_K
            
    path = mode + '_error_df' + 'J' + str(J) + 'K' +  str(K) +'M' + str(M)+str(dg).split()[1] +'.csv'
    df = pd.read_csv(path)
    print(mode, df.mean())

endo Unnamed: 0         0.0000
J                 10.0000
K                 11.0000
M                100.0000
seed          368952.0000
mse_deep           0.0194
mae_deep           0.0256
dtype: float64
comp Unnamed: 0         0.0000
J                 10.0000
K                 11.0000
M                100.0000
seed          368952.0000
mse_deep           0.0195
mae_deep           0.0254
dtype: float64
wrong Unnamed: 0         0.0000
J                 10.0000
K                 10.6667
M                100.0000
seed          368952.0000
mse_deep           0.0202
mae_deep           0.0263
dtype: float64

/tmp/ipykernel_444328/4197927551.py:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(mode, df.mean())
/tmp/ipykernel_444328/4197927551.py:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(mode, df.mean())
/tmp/ipykernel_444328/4197927551.py:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(mode, df.mean())

In [41]:
df #comp

    type  ae_deep
0  cross   0.0657
1   self   0.2290

In [39]:
df#wrong

    type  ae_deep
0  cross   1.9751
1   self   2.3832

In [37]:
df#endo

    type  ae_deep
0  cross   0.0669
1   self   0.2307